CREATE TABLE USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME TEXT NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL
);

CREATE TABLE USER_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLES TEXT NOT NULL
);